package export

import (
	"bytes"
	"encoding/csv"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/dylanbr0wn/shsh/internal/store"
)

// ExportRecord is a credential-free, serialisable view of one host.
type ExportRecord struct {
	Label      string
	Hostname   string
	Port       int
	Username   string
	AuthMethod store.AuthMethod
	KeyPath    string // empty if not key auth
	Tags       []string
	GroupName  string // empty if ungrouped
	Color      string
}

// BuildRecords converts raw hosts and groups into export records.
// groups is used only for resolving group names; the caller is responsible for
// any filtering (by group or by selected host IDs) before calling this function.
func BuildRecords(hosts []store.Host, groups []store.Group) []ExportRecord {
	groupNames := make(map[string]string, len(groups))
	for _, g := range groups {
		groupNames[g.ID] = g.Name
	}

	records := make([]ExportRecord, 0, len(hosts))
	for _, h := range hosts {
		r := ExportRecord{
			Label:      h.Label,
			Hostname:   h.Hostname,
			Port:       h.Port,
			Username:   h.Username,
			AuthMethod: h.AuthMethod,
			Color:      h.Color,
		}
		if h.Tags != nil {
			r.Tags = h.Tags
		}
		if h.KeyPath != nil {
			r.KeyPath = *h.KeyPath
		}
		if h.GroupID != nil {
			r.GroupName = groupNames[*h.GroupID]
		}
		records = append(records, r)
	}
	return records
}

// SSHConfig renders records as an OpenSSH-compatible config block.
// Hosts are clustered under their group (commented header). Ungrouped hosts
// appear at the end. Port is omitted when it equals 22. IdentityFile is only
// emitted for key-auth hosts.
func SSHConfig(records []ExportRecord) ([]byte, error) {
	// Collect aliases first so we can deduplicate.
	aliases := buildAliases(records)

	// Group order: named groups first (stable, alpha), then ungrouped.
	type groupBucket struct {
		name    string
		indices []int
	}
	buckets := map[string]*groupBucket{}
	var order []string
	const ungrouped = "\x00ungrouped"

	for i, r := range records {
		key := r.GroupName
		if key == "" {
			key = ungrouped
		}
		if _, ok := buckets[key]; !ok {
			buckets[key] = &groupBucket{name: r.GroupName}
			order = append(order, key)
		}
		buckets[key].indices = append(buckets[key].indices, i)
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by shsh — https://github.com/dylanbr0wn/shsh\n")

	for _, key := range order {
		bucket := buckets[key]
		if key == ungrouped {
			buf.WriteString("\n# Ungrouped\n")
		} else {
			fmt.Fprintf(&buf, "\n# Group: %s\n", bucket.name)
		}

		for _, idx := range bucket.indices {
			r := records[idx]
			alias := aliases[idx]
			fmt.Fprintf(&buf, "\nHost %s\n", alias)
			fmt.Fprintf(&buf, "    HostName %s\n", r.Hostname)
			if r.Port != 22 {
				fmt.Fprintf(&buf, "    Port %d\n", r.Port)
			}
			fmt.Fprintf(&buf, "    User %s\n", r.Username)
			if r.AuthMethod == store.AuthKey && r.KeyPath != "" {
				fmt.Fprintf(&buf, "    IdentityFile %s\n", r.KeyPath)
			}
		}
	}

	return buf.Bytes(), nil
}

// buildAliases returns a sanitised, deduplicated alias for each record.
// Spaces become dashes; glob characters are stripped. Duplicates are resolved
// by appending the hostname.
func buildAliases(records []ExportRecord) []string {
	aliases := make([]string, len(records))
	seen := map[string]int{} // alias → first index that claimed it

	for i, r := range records {
		alias := sanitiseAlias(r.Label)
		if alias == "" {
			alias = sanitiseAlias(r.Hostname)
		}
		if prev, conflict := seen[alias]; conflict {
			// Disambiguate both the previous claimant and this one.
			if aliases[prev] == alias {
				aliases[prev] = alias + "-" + sanitiseAlias(records[prev].Hostname)
			}
			alias = alias + "-" + sanitiseAlias(r.Hostname)
		}
		seen[alias] = i
		aliases[i] = alias
	}
	return aliases
}

func sanitiseAlias(s string) string {
	s = strings.ReplaceAll(s, " ", "-")
	s = strings.ReplaceAll(s, "*", "")
	s = strings.ReplaceAll(s, "?", "")
	return s
}

// jsonExport is the envelope written for JSON exports.
type jsonExport struct {
	Version    int            `json:"version"`
	ExportedAt string         `json:"exportedAt"`
	Hosts      []jsonHostItem `json:"hosts"`
}

type jsonHostItem struct {
	Label      string   `json:"label"`
	Hostname   string   `json:"hostname"`
	Port       int      `json:"port"`
	Username   string   `json:"username"`
	AuthMethod string   `json:"authMethod"`
	KeyPath    string   `json:"keyPath,omitempty"`
	Tags       []string `json:"tags,omitempty"`
	Group      string   `json:"group,omitempty"`
	Color      string   `json:"color,omitempty"`
}

// JSON renders records as a structured JSON array with a versioned envelope.
func JSON(records []ExportRecord) ([]byte, error) {
	items := make([]jsonHostItem, len(records))
	for i, r := range records {
		items[i] = jsonHostItem{
			Label:      r.Label,
			Hostname:   r.Hostname,
			Port:       r.Port,
			Username:   r.Username,
			AuthMethod: string(r.AuthMethod),
			KeyPath:    r.KeyPath,
			Tags:       r.Tags,
			Group:      r.GroupName,
			Color:      r.Color,
		}
	}
	env := jsonExport{
		Version:    1,
		ExportedAt: time.Now().UTC().Format(time.RFC3339),
		Hosts:      items,
	}
	return json.MarshalIndent(env, "", "  ")
}

// CSV renders records as a UTF-8 comma-separated table.
// Tags are joined with "|" within the cell.
func CSV(records []ExportRecord) ([]byte, error) {
	var buf bytes.Buffer
	w := csv.NewWriter(&buf)

	if err := w.Write([]string{"label", "hostname", "port", "username", "auth_method", "key_path", "tags", "group", "color"}); err != nil {
		return nil, err
	}
	for _, r := range records {
		row := []string{
			r.Label,
			r.Hostname,
			fmt.Sprintf("%d", r.Port),
			r.Username,
			string(r.AuthMethod),
			r.KeyPath,
			strings.Join(r.Tags, "|"),
			r.GroupName,
			r.Color,
		}
		if err := w.Write(row); err != nil {
			return nil, err
		}
	}
	w.Flush()
	return buf.Bytes(), w.Error()
}
