/* eslint-disable @typescript-eslint/no-explicit-any */
// Stub — replaced by vi.mock in setup.ts at runtime.
export const ListHosts = (..._args: any[]): Promise<any> => Promise.resolve([])
export const ListGroups = (..._args: any[]): Promise<any> => Promise.resolve([])
export const ListTerminalProfiles = (..._args: any[]): Promise<any> => Promise.resolve([])
export const ListWorkspaceTemplates = (..._args: any[]): Promise<any> => Promise.resolve([])
export const AddGroup = (..._args: any[]): Promise<any> => Promise.resolve()
export const PingHosts = (..._args: any[]): Promise<any> => Promise.resolve({})
export const DeleteHost = (..._args: any[]): Promise<any> => Promise.resolve()
export const UpdateHost = (..._args: any[]): Promise<any> => Promise.resolve()
export const AddHost = (..._args: any[]): Promise<any> => Promise.resolve()
export const DeleteGroup = (..._args: any[]): Promise<any> => Promise.resolve()
export const UpdateGroup = (..._args: any[]): Promise<any> => Promise.resolve()
export const SaveWorkspaceTemplate = (..._args: any[]): Promise<any> => Promise.resolve()
export const ListSSHConfigHosts = (..._args: any[]): Promise<any> => Promise.resolve([])
export const ImportSSHConfigHosts = (..._args: any[]): Promise<any> => Promise.resolve()
export const AddTerminalProfile = (..._args: any[]): Promise<any> => Promise.resolve()
export const UpdateTerminalProfile = (..._args: any[]): Promise<any> => Promise.resolve()
export const DeleteTerminalProfile = (..._args: any[]): Promise<any> => Promise.resolve()
