// Stub — replaced by vi.mock in setup.ts at runtime.
export const ListHosts = (): Promise<unknown[]> => Promise.resolve([])
export const ListGroups = (): Promise<unknown[]> => Promise.resolve([])
export const ListTerminalProfiles = (): Promise<unknown[]> => Promise.resolve([])
export const ListWorkspaceTemplates = (): Promise<unknown[]> => Promise.resolve([])
export const AddGroup = (): Promise<void> => Promise.resolve()
export const PingHosts = (): Promise<Record<string, unknown>> => Promise.resolve({})
export const DeleteHost = (): Promise<void> => Promise.resolve()
export const UpdateHost = (): Promise<void> => Promise.resolve()
export const AddHost = (): Promise<void> => Promise.resolve()
export const DeleteGroup = (): Promise<void> => Promise.resolve()
export const UpdateGroup = (): Promise<void> => Promise.resolve()
export const SaveWorkspaceTemplate = (): Promise<void> => Promise.resolve()
export const ListSSHConfigHosts = (): Promise<unknown[]> => Promise.resolve([])
export const ImportSSHConfigHosts = (): Promise<void> => Promise.resolve()
