/* eslint-disable @typescript-eslint/no-explicit-any */
// Stub — replaced by vi.mock in setup.ts at runtime.
export const CloseChannel = (..._args: any[]): Promise<any> => Promise.resolve()
export const ConnectHost = (..._args: any[]): Promise<any> => Promise.resolve()
export const WriteToChannel = (..._args: any[]): Promise<any> => Promise.resolve()
export const ResizeChannel = (..._args: any[]): Promise<any> => Promise.resolve()
export const ListPortForwards = (..._args: any[]): Promise<any> => Promise.resolve([])
export const RemovePortForward = (..._args: any[]): Promise<any> => Promise.resolve()
export const StartSessionLog = (..._args: any[]): Promise<any> => Promise.resolve('')
export const StopSessionLog = (..._args: any[]): Promise<any> => Promise.resolve()
export const ListSFTPDir = (..._args: any[]): Promise<any> => Promise.resolve([])
export const DownloadFile = (..._args: any[]): Promise<any> => Promise.resolve()
export const UploadFile = (..._args: any[]): Promise<any> => Promise.resolve()
export const ConnectForSFTP = (..._args: any[]): Promise<any> => Promise.resolve()
export const QuickConnect = (..._args: any[]): Promise<any> => Promise.resolve()
export const AddPortForward = (..._args: any[]): Promise<any> => Promise.resolve()
export const RespondHostKey = (..._args: any[]): Promise<any> => Promise.resolve()
export const OpenTerminal = (..._args: any[]): Promise<any> => Promise.resolve()
export const OpenSFTPChannel = (..._args: any[]): Promise<any> => Promise.resolve()
export const OpenLocalFSChannel = (..._args: any[]): Promise<any> => Promise.resolve()
export const SFTPListDir = (..._args: any[]): Promise<any> => Promise.resolve([])
export const SFTPDownload = (..._args: any[]): Promise<any> => Promise.resolve()
export const SFTPDownloadDir = (..._args: any[]): Promise<any> => Promise.resolve()
export const SFTPUpload = (..._args: any[]): Promise<any> => Promise.resolve()
export const SFTPUploadPath = (..._args: any[]): Promise<any> => Promise.resolve()
export const SFTPMkdir = (..._args: any[]): Promise<any> => Promise.resolve()
export const SFTPDelete = (..._args: any[]): Promise<any> => Promise.resolve()
export const SFTPRename = (..._args: any[]): Promise<any> => Promise.resolve()
export const TransferBetweenChannels = (..._args: any[]): Promise<any> => Promise.resolve()
export const LocalListDir = (..._args: any[]): Promise<any> => Promise.resolve([])
export const LocalMkdir = (..._args: any[]): Promise<any> => Promise.resolve()
export const LocalDelete = (..._args: any[]): Promise<any> => Promise.resolve()
export const LocalRename = (..._args: any[]): Promise<any> => Promise.resolve()
export const SFTPPreviewFile = (..._args: any[]): Promise<any> => Promise.resolve({ name: '', size: 0, mimeType: 'text/plain', content: '' })
export const LocalPreviewFile = (..._args: any[]): Promise<any> => Promise.resolve({ name: '', size: 0, mimeType: 'text/plain', content: '' })
