// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGroup(arg1) {
  return window['go']['main']['App']['AddGroup'](arg1);
}

export function AddHost(arg1) {
  return window['go']['main']['App']['AddHost'](arg1);
}

export function AddPortForward(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddPortForward'](arg1, arg2, arg3, arg4);
}

export function BulkConnectGroup(arg1) {
  return window['go']['main']['App']['BulkConnectGroup'](arg1);
}

export function CloseSFTP(arg1) {
  return window['go']['main']['App']['CloseSFTP'](arg1);
}

export function ConnectHost(arg1) {
  return window['go']['main']['App']['ConnectHost'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteHost(arg1) {
  return window['go']['main']['App']['DeleteHost'](arg1);
}

export function DisconnectSession(arg1) {
  return window['go']['main']['App']['DisconnectSession'](arg1);
}

export function ImportSSHConfigHosts(arg1) {
  return window['go']['main']['App']['ImportSSHConfigHosts'](arg1);
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListHosts() {
  return window['go']['main']['App']['ListHosts']();
}

export function ListPortForwards(arg1) {
  return window['go']['main']['App']['ListPortForwards'](arg1);
}

export function ListSSHConfigHosts() {
  return window['go']['main']['App']['ListSSHConfigHosts']();
}

export function OpenSFTP(arg1) {
  return window['go']['main']['App']['OpenSFTP'](arg1);
}

export function RemovePortForward(arg1, arg2) {
  return window['go']['main']['App']['RemovePortForward'](arg1, arg2);
}

export function ResizeSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeSession'](arg1, arg2, arg3);
}

export function RespondHostKey(arg1, arg2) {
  return window['go']['main']['App']['RespondHostKey'](arg1, arg2);
}

export function SFTPDelete(arg1, arg2) {
  return window['go']['main']['App']['SFTPDelete'](arg1, arg2);
}

export function SFTPDownload(arg1, arg2) {
  return window['go']['main']['App']['SFTPDownload'](arg1, arg2);
}

export function SFTPDownloadDir(arg1, arg2) {
  return window['go']['main']['App']['SFTPDownloadDir'](arg1, arg2);
}

export function SFTPListDir(arg1, arg2) {
  return window['go']['main']['App']['SFTPListDir'](arg1, arg2);
}

export function SFTPMkdir(arg1, arg2) {
  return window['go']['main']['App']['SFTPMkdir'](arg1, arg2);
}

export function SFTPRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPRename'](arg1, arg2, arg3);
}

export function SFTPUpload(arg1, arg2) {
  return window['go']['main']['App']['SFTPUpload'](arg1, arg2);
}

export function UpdateGroup(arg1) {
  return window['go']['main']['App']['UpdateGroup'](arg1);
}

export function UpdateHost(arg1) {
  return window['go']['main']['App']['UpdateHost'](arg1);
}

export function WriteToSession(arg1, arg2) {
  return window['go']['main']['App']['WriteToSession'](arg1, arg2);
}
