// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddHost(arg1:main.CreateHostInput):Promise<main.Host>;

export function CloseSFTP(arg1:string):Promise<void>;

export function ConnectHost(arg1:string):Promise<string>;

export function DeleteHost(arg1:string):Promise<void>;

export function DisconnectSession(arg1:string):Promise<void>;

export function ImportSSHConfigHosts(arg1:Array<string>):Promise<Array<main.Host>>;

export function ListHosts():Promise<Array<main.Host>>;

export function ListSSHConfigHosts():Promise<Array<main.SSHConfigEntry>>;

export function OpenSFTP(arg1:string):Promise<void>;

export function ResizeSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RespondHostKey(arg1:string,arg2:boolean):Promise<void>;

export function SFTPDelete(arg1:string,arg2:string):Promise<void>;

export function SFTPDownload(arg1:string,arg2:string):Promise<void>;

export function SFTPDownloadDir(arg1:string,arg2:string):Promise<void>;

export function SFTPListDir(arg1:string,arg2:string):Promise<Array<main.SFTPEntry>>;

export function SFTPMkdir(arg1:string,arg2:string):Promise<void>;

export function SFTPRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPUpload(arg1:string,arg2:string):Promise<void>;

export function UpdateHost(arg1:main.UpdateHostInput):Promise<main.Host>;

export function WriteToSession(arg1:string,arg2:string):Promise<void>;
