// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {session} from '../models';
import {main} from '../models';
import {credstore} from '../models';
import {config} from '../models';
import {sshconfig} from '../models';

export function AddGroup(arg1:store.CreateGroupInput):Promise<store.Group>;

export function AddHost(arg1:store.CreateHostInput):Promise<store.Host>;

export function AddPortForward(arg1:string,arg2:number,arg3:string,arg4:number):Promise<session.PortForwardInfo>;

export function AddTerminalProfile(arg1:store.CreateProfileInput):Promise<store.TerminalProfile>;

export function BrowseKeyFile():Promise<string>;

export function BulkConnectGroup(arg1:string):Promise<Array<main.BulkConnectResult>>;

export function CheckPasswordManagers():Promise<credstore.PasswordManagersStatus>;

export function CloseChannel(arg1:string):Promise<void>;

export function ConnectForSFTP(arg1:string):Promise<session.ConnectHostResult>;

export function ConnectHost(arg1:string):Promise<session.ConnectHostResult>;

export function DeleteGroup(arg1:string):Promise<void>;

export function DeleteHost(arg1:string):Promise<void>;

export function DeleteSessionLog(arg1:string):Promise<void>;

export function DeleteTerminalProfile(arg1:string):Promise<void>;

export function DeleteWorkspaceTemplate(arg1:string):Promise<void>;

export function DeployPublicKey(arg1:string,arg2:string):Promise<string>;

export function ExportHosts(arg1:main.ExportInput):Promise<string>;

export function GenerateSSHKey(arg1:main.GenerateKeyInput):Promise<main.GenerateKeyResult>;

export function GetConfig():Promise<config.Config>;

export function GetHomeDir():Promise<string>;

export function GetSessionLogPath(arg1:string):Promise<string>;

export function ImportSSHConfigHosts(arg1:Array<string>):Promise<Array<store.Host>>;

export function ListGroups():Promise<Array<store.Group>>;

export function ListHosts():Promise<Array<store.Host>>;

export function ListPortForwards(arg1:string):Promise<Array<session.PortForwardInfo>>;

export function ListSSHConfigHosts():Promise<Array<sshconfig.Entry>>;

export function ListSessionLogs():Promise<Array<main.LogFileInfo>>;

export function ListTerminalProfiles():Promise<Array<store.TerminalProfile>>;

export function ListWorkspaceTemplates():Promise<Array<store.WorkspaceTemplate>>;

export function LocalDelete(arg1:string,arg2:string):Promise<void>;

export function LocalListDir(arg1:string,arg2:string):Promise<Array<session.SFTPEntry>>;

export function LocalMkdir(arg1:string,arg2:string):Promise<void>;

export function LocalRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenLocalFSChannel():Promise<string>;

export function OpenLogsDirectory():Promise<void>;

export function OpenSFTPChannel(arg1:string):Promise<string>;

export function OpenTerminal(arg1:string):Promise<string>;

export function PingHosts(arg1:Array<string>):Promise<Array<main.PingResult>>;

export function QuickConnect(arg1:main.QuickConnectInput):Promise<session.ConnectHostResult>;

export function ReadPublicKeyText(arg1:string):Promise<string>;

export function ReadSessionLog(arg1:string):Promise<string>;

export function RemovePortForward(arg1:string,arg2:string):Promise<void>;

export function ResizeChannel(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RespondHostKey(arg1:string,arg2:boolean):Promise<void>;

export function SFTPDelete(arg1:string,arg2:string):Promise<void>;

export function SFTPDownload(arg1:string,arg2:string):Promise<void>;

export function SFTPDownloadDir(arg1:string,arg2:string):Promise<void>;

export function SFTPListDir(arg1:string,arg2:string):Promise<Array<session.SFTPEntry>>;

export function SFTPMkdir(arg1:string,arg2:string):Promise<void>;

export function SFTPRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPUpload(arg1:string,arg2:string):Promise<void>;

export function SFTPUploadPath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveWorkspaceTemplate(arg1:store.CreateTemplateInput):Promise<store.WorkspaceTemplate>;

export function StartSessionLog(arg1:string):Promise<string>;

export function StopSessionLog(arg1:string):Promise<void>;

export function TestCredentialRef(arg1:string,arg2:string):Promise<void>;

export function TestHostCredential(arg1:string):Promise<void>;

export function TransferBetweenChannels(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function TransferBetweenHosts(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateConfig(arg1:config.Config):Promise<void>;

export function UpdateGroup(arg1:store.UpdateGroupInput):Promise<store.Group>;

export function UpdateHost(arg1:store.UpdateHostInput):Promise<store.Host>;

export function UpdateTerminalProfile(arg1:store.UpdateProfileInput):Promise<store.TerminalProfile>;

export function WriteToChannel(arg1:string,arg2:string):Promise<void>;
